# https://gitlab.com/pages/mkdocs/blob/master/.gitlab-ci.yml
#	= ^ . ^ =
image: python:3.10-slim-bullseye

before_script:
- cp -vf .apt.conf.d/99-local /etc/apt/apt.conf.d/99-local
- apt update
- apt install make
- pip config --global set global.progress_bar off
- pip install --quiet --upgrade pip
- pip install --quiet --requirement requirements.txt

test:
  stage: test
  script:
  - make test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - public
  only:
  - main
