# https://gitlab.com/pages/mkdocs/blob/master/.gitlab-ci.yml
#	= ^ . ^ =
image: python:3.10-alpine

before_script:
- apk --quiet --no-progress update
- apk --quiet --no-progress add bash make
- pip config --global set global.progress_bar off
- pip install --quiet --upgrade pip
- pip install --quiet --requirement requirements.txt

test:
  stage: test
  script:
  - make test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - public
  only:
  - main
