# https://www.mkdocs.org/user-guide/configuration/
repo_name: mkdocs.gitlab.io
repo_url: https://gitlab.com/tonejito/mkdocs.gitlab.io
edit_uri: -/tree/master/docs

site_name: mkdocs
site_description: Documentación de proyectos con Markdown
copyright: CC-BY-SA-4.0
site_url: https://mkdocs.gitlab.io
site_dir: public
docs_dir: docs

extra_css:
- css/extra.css

extra_javascript:
- js/extra.js

# https://www.mkdocs.org/user-guide/choosing-your-theme/
theme:
  name: mkdocs
  # name: readthedocs
  locale: es
  navigation_depth: 4
  collapse_navigation: true
  titles_only: true

markdown_extensions:
- toc:
    permalink: "#"
    separator: "-"
